// nuxtjs-frontend/pages/my-todo/[id].vue
<template>
  <div>
    <Header />
    <Section>
      <Container>
        <div class="back" @click="goBack">
          <IoIosArrowBack :size="25" color="teal" />
        </div>

        <div v-if="todo">
          <p>Task:</p>
          <Title :title="todo.title" />
          <p>Is completed:</p>
          <Title
            :title="
              todo.isCompleted
                ? 'Task is completed'
                : 'You should finish the task'
            "
          />
        </div>
      </Container>
    </Section>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from "vue";
import { IoIosArrowBack } from "vue3-icons/io";

import { todoListApi } from "../utils/utils/todoApi";
import type ITodo from "../utils/interfaces/Todo.interface";

import Header from "../components/Header.vue";
import Section from "../components/Section.vue";
import Container from "../components/Container.vue";
import Title from "../components/Title.vue";

const router = useRouter();
const route = useRoute();

const todo = ref<ITodo | null>(null);

const goBack = () => {
  router.push("/my-todo-list");
};

onMounted(async () => {
  const todoId = route.params.id as string | undefined;
  const token = localStorage.getItem("token");

  if (!todoId || !token) return;

  try {
    const response = await todoListApi.getByid(todoId, token);
    todo.value = response.data.todo;
  } catch (error) {
    console.error(error);
  }
});
</script>

<style scoped lang="scss">
.back {
  margin-bottom: 40px;
  cursor: pointer;
}
</style>

// nextjs-frontend/pages/my-todo-list/[id].tsx
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { IoIosArrowBack } from "react-icons/io";

import styled from "styled-components";
import ITodo from "../../../shared/interfaces/Todo.interface";
import { todoListApi } from "../../../shared/utils/todoApi";
import Header from "../../src/components/Header";
import Section from "../../src/components/Section";
import Container from "../../src/components/Container";
import Title from "../../src/components/Title";


const Back = styled.div`
  margin-bottom: 40px;
  cursor: pointer;
`;

const Id = () => {
  const [todo, setTodo] = useState<ITodo>(null);
  const router = useRouter();

  const { id } = router.query;

  const getTodo = async () => {
    const token = localStorage.getItem("token");
    const todo = await todoListApi.getByid(id, token);
    setTodo(todo.data.todo);
  };

  useEffect(() => {
    if (id) {
      getTodo();
    }
  }, [id]);

  return (
    <>
      <Header />
      <Section>
        <Container>
          <Back
            onClick={() => {
              router.push("/my-todo-list");
            }}
          >
            <IoIosArrowBack size={25} color={"teal"} />
          </Back>
          {todo && (
            <>
              <p>Task:</p>
              <Title title={todo.title} />
              <p>Is completed:</p>
              {todo.isCompleted ? (
                <Title title={"Task is completed"} />
              ) : (
                <Title title={"You should finish the task"} />
              )}
            </>
          )}
        </Container>
      </Section>
    </>
  );
};

export default Id;
