// nuxtjs-frontend/components/Header.vue
<template>
  <div class="header">
    <div class="btn" @click="logout">
      <p>Log out</p>
    </div>
  </div>
</template>

<script setup lang="ts">
import { authApi } from "../utils/utils/authApi";

// Function to handle logout
// This function will remove the token from localStorage and redirect to the login page
const router = useRouter();

const logout = async () => {
  const token = localStorage.getItem("token");

  if (token) {
    await authApi.logout(token);
  } else {
    console.warn("No token found, skipping logout.");
  }

  localStorage.removeItem("token");
  router.push("/login");
};
</script>

<style scoped lang="scss">
.header {
  padding: 15px;
  display: flex;
  justify-content: space-between;
  background-color: #c0d1c2;
  cursor: pointer;
  transition: opacity 250ms cubic-bezier(0.445, 0.05, 0.55, 0.95);
  &:hover,
  &:focus {
    opacity: 0.6;
  }
}
.btn {
  display: flex;
  align-items: center;
  gap: 10px;
  margin-left: auto;
  p {
    font-size: 16px;
  }
}
</style>

// react-frontend/src/components/Header.tsx
import styled from "styled-components";
import { AiOutlineLogout } from "react-icons/ai";
import { useNavigate } from "react-router-dom";

import { authApi } from "../utils/utils/authApi";

const HeaderWrap = styled.div`
  padding: 15px;
  display: flex;
  justify-content: space-between;
  background-color: #c0d1c2;
  cursor: pointer;
  transition: opacity 250ms cubic-bezier(0.445, 0.05, 0.55, 0.95);
  &:hover,
  &:focus {
    opacity: 0.6;
  }
`;
const BtnWrap = styled.div`
  display: flex;
  align-items: center;
  gap: 10px;
  margin-left: auto;
  p {
    font-size: 16px;
  }
`;

const Header = () => {
  const navigate = useNavigate();
  const logout = async () => {
    const token = localStorage.getItem("token");

    if (token) {
      authApi.logout(token);
    } else {
      console.warn("No token found, skipping logout.");
    }

    navigate("/login");

    localStorage.removeItem("token");
  };

  return (
    <HeaderWrap>
      <BtnWrap onClick={logout}>
        <p>{"Log out"}</p>
        <AiOutlineLogout size={20} />
      </BtnWrap>
    </HeaderWrap>
  );
};

export default Header;
