// vue-frontend/src/components/LoginForm.vue
<template>
  <Section>
    <Container>
      <PopUp v-if="error" error="Email or password is incorrect" />

      <div class="form-wrap">
        <FormTitle title="Welcome back :)" />

        <Form @submit="onSubmit" :validation-schema="schema" v-slot="{ values  }" validate-on-blur
  validate-on-change
  validate-on-input>
          <Input style="margin: 0 auto 30px">
            <Field
              name="email"
              type="text"
              placeholder="Email"
              autocomplete="email"
            />
            <ErrorMessage name="email" class="error-text" />
          </Input>

          <Input style="margin: 0 auto 30px">
            <div style="position: relative">
              <Field
                :type="type"
                name="password"
                placeholder="Password"
                autocomplete="password"
              />
              <Icon :type="type" @click="toggleType" />
              <ErrorMessage name="password" class="error-text" />
            </div>
          </Input>

          <SubmitBtn title="Log in" type="submit" />
        </Form>

        <LinkText>
          Don’t have an account?
          <RouterLink to="/"> Register</RouterLink>
        </LinkText>
      </div>
    </Container>
  </Section>
</template>

<script setup lang="ts">
import { ref } from "vue";
import { useRouter } from "vue-router";
import { useForm, Field, Form, ErrorMessage } from "vee-validate";
import * as Yup from "yup";
import axios from "axios";

import Section from "./Section.vue";
import Container from "./Container.vue";
import Input from "./Input.vue";
import LinkText from "./LinkText.vue";
import FormTitle from "./FormTitle.vue";
import Icon from "./Icon.vue";
import SubmitBtn from "./SubmitBtn.vue";
import PopUp from "./PopUp.vue";

import { authApi } from "../utils/utils/authApi";

const router = useRouter();

const type = ref<"password" | "text">("password");
const error = ref<string | null>(null);

const toggleType = () => {
  type.value = type.value === "password" ? "text" : "password";
};

const schema = Yup.object({
  email: Yup.string().required("Email is required"),
  password: Yup.string().required("Password is required"),
});

// const { handleSubmit } = useForm({
//   validationSchema: schema,
// });

const onSubmit = async (values) => {

  try {
  console.log(error);

    const res = await authApi.login(values);
    console.log(res);

    // localStorage.setItem("token", res.token);
    // router.push("/my-todo-list");
  } catch (e) {
    if (axios.isAxiosError(e)) {
      error.value = e.response?.data || "Login failed";
    }
  }
};
</script>

<style scoped>
.form-wrap {
  padding: 200px 0;
}
.error-text {
  color: red;
  font-size: 13px;
  margin-top: 4px;
  display: block;
}
</style>

// react-frontend/src/components/LoginForm.tsx
import * as Yup from "yup";
import { Formik, Form, Field } from "formik";
import { useState } from "react";
import styled from "styled-components";
import { Link, useNavigate } from "react-router-dom";
import axios from "axios";

import { authApi } from "../utils/utils/authApi";
import type TInputType from "../utils/types/Password.type";

import Container from "./Container";
import Input from "./Input";
import LinkText from "./LinkText";
import FormTitle from "./FormTitle";
import Icon from "./Icon";
import SubmitBtn from "./SubmitBtn";
import PopUp from "./PopUp";
import Section from "./Section";

const FormWrap = styled.div`
  padding: 200px 0;
`;

interface IUser {
  email: string;
  password: string;
}

const LoginForm = () => {
  const navigate = useNavigate();

  const [type, setType] = useState<TInputType>("password");
  const [error, setError] = useState(null);

  const toggleType = () =>
    type === "password" ? setType("text") : setType("password");

  const login = async (values: IUser) => {
    try {
      const res = await authApi.login(values);
      localStorage.setItem("token", res.token);
      navigate("/my-todo-list");
    } catch (e) {
      if (axios.isAxiosError(e)) {
        setError(e.response?.data);
      }
    }
  };

  return (
    <Section>
      <Container>
        {error && <PopUp error={"Email or password is incorrect"} />}
        <FormWrap>
          <FormTitle title={"Welcome back :)"} />
          <Formik
            initialValues={{
              email: "",
              password: "",
            }}
            validationSchema={Yup.object().shape({
              email: Yup.string().required().label("Email"),
              password: Yup.string().required().label("Password"),
            })}
            onSubmit={(values) => login(values)}
            validateOnChange={true}
          >
            {({ handleChange, handleSubmit, handleBlur, values }) => {
              return (
                <Form>
                  <Input style={{ margin: "0 auto 30px" }}>
                    <Field
                      type="text"
                      name="email"
                      onChange={handleChange}
                      onBlur={handleBlur}
                      value={values.email}
                      placeholder={"Email"}
                      autoComplete="email"
                    />
                  </Input>

                  <Input style={{ margin: "0 auto 30px" }}>
                    <div>
                      <Field
                        type={type}
                        name="password"
                        onChange={handleChange}
                        onBlur={handleBlur}
                        value={values.password}
                        placeholder={"Password"}
                        autoComplete="password"
                      />
                      <Icon onClick={toggleType} type={type} />
                    </div>
                  </Input>

                  <SubmitBtn
                    title={"Log in"}
                    type="submit"
                    onClick={handleSubmit}
                  />
                </Form>
              );
            }}
          </Formik>
          <LinkText>
            {"Don't have an account?"}
            <Link to={"/register"}> {"Register"}</Link>
          </LinkText>
        </FormWrap>
      </Container>
    </Section>
  );
};

export default LoginForm;
