// angular-frontend/src/app/components/login-form/login-form.ts
import { Component } from '@angular/core';
import {
  FormBuilder,
  FormGroup,
  Validators,
  ReactiveFormsModule,
} from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { CommonModule } from '@angular/common';

import { authApi } from '../../utils/utils/authApi';

import { Section } from '../section/section';
import { Container } from '../container/container';
import { FormTitle } from '../form-title/form-title';
import { Icon } from '../icon/icon';
import { CustomInput } from '../custom-input/custom-input';
import { SubmitBtn } from '../submit-btn/submit-btn';
import { LinkText } from '../link-text/link-text';
import { PopUp } from '../pop-up/pop-up';

@Component({
  selector: 'app-login-form',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    Section,
    Container,
    FormTitle,
    Icon,
    CustomInput,
    SubmitBtn,
    LinkText,
    RouterModule,
    PopUp,
  ],
  templateUrl: './login-form.html',
  styleUrl: './login-form.scss',
})
export class LoginForm {
  error: string | null = null;
  type: 'password' | 'text' = 'password';
  form: FormGroup;

  constructor(private fb: FormBuilder, private router: Router) {
    this.form = this.fb.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', Validators.required],
    });
  }

  toggleType(): void {
    this.type = this.type === 'password' ? 'text' : 'password';
  }

  async onSubmit(): Promise<void> {
    if (this.form.invalid) return;

    try {
      const res = await authApi.login(this.form.value);
      localStorage.setItem('token', res.token);
      this.router.navigate(['/my-todo-list']);
    } catch (err) {
      this.error = 'Email or password is incorrect';
    }
  }
}

// react-frontend/src/components/LoginForm.tsx
import * as Yup from "yup";
import { Formik, Form, Field } from "formik";
import { useState } from "react";
import styled from "styled-components";
import { Link, useNavigate } from "react-router-dom";
import axios from "axios";

import { authApi } from "../utils/utils/authApi";
import type TInputType from "../utils/types/Password.type";

import Container from "./Container";
import Input from "./Input";
import LinkText from "./LinkText";
import FormTitle from "./FormTitle";
import Icon from "./Icon";
import SubmitBtn from "./SubmitBtn";
import PopUp from "./PopUp";
import Section from "./Section";

const FormWrap = styled.div`
  padding: 200px 0;
`;

interface IUser {
  email: string;
  password: string;
}

const LoginForm = () => {
  const navigate = useNavigate();

  const [type, setType] = useState<TInputType>("password");
  const [error, setError] = useState(null);

  const toggleType = () =>
    type === "password" ? setType("text") : setType("password");

  const login = async (values: IUser) => {
    try {
      const res = await authApi.login(values);
      localStorage.setItem("token", res.token);
      navigate("/my-todo-list");
    } catch (e) {
      if (axios.isAxiosError(e)) {
        setError(e.response?.data);
      }
    }
  };

  return (
    <Section>
      <Container>
        {error && <PopUp error={"Email or password is incorrect"} />}
        <FormWrap>
          <FormTitle title={"Welcome back :)"} />
          <Formik
            initialValues={{
              email: "",
              password: "",
            }}
            validationSchema={Yup.object().shape({
              email: Yup.string().required().label("Email"),
              password: Yup.string().required().label("Password"),
            })}
            onSubmit={(values) => login(values)}
            validateOnChange={true}
          >
            {({ handleChange, handleSubmit, handleBlur, values }) => {
              return (
                <Form>
                  <Input style={{ margin: "0 auto 30px" }}>
                    <Field
                      type="text"
                      name="email"
                      onChange={handleChange}
                      onBlur={handleBlur}
                      value={values.email}
                      placeholder={"Email"}
                      autoComplete="email"
                    />
                  </Input>

                  <Input style={{ margin: "0 auto 30px" }}>
                    <div>
                      <Field
                        type={type}
                        name="password"
                        onChange={handleChange}
                        onBlur={handleBlur}
                        value={values.password}
                        placeholder={"Password"}
                        autoComplete="password"
                      />
                      <Icon onClick={toggleType} type={type} />
                    </div>
                  </Input>

                  <SubmitBtn
                    title={"Log in"}
                    type="submit"
                    onClick={handleSubmit}
                  />
                </Form>
              );
            }}
          </Formik>
          <LinkText>
            {"Don't have an account?"}
            <Link to={"/register"}> {"Register"}</Link>
          </LinkText>
        </FormWrap>
      </Container>
    </Section>
  );
};

export default LoginForm;
