// vue-frontend/src/components/RegisterForm.vue
<template>
  <Section>
    <Container>
      <FormTitle title="Create your own TODO list :)" />
      <Form @submit="onSubmit" class="wrap" :validation-schema="schema" v-slot="{ values  }" validate-on-blur
  validate-on-change
  validate-on-input>
        <Input>
          <Field name="firstName" v-slot="{ field, errorMessage, meta }">
            <input v-bind="field" placeholder="First Name" />
            <p v-if="meta.touched && errorMessage" class="error">{{ errorMessage }}</p>
          </Field>
       </Input>

        <Input>
          <Field name="lastName" v-slot="{ field, errorMessage, meta }">
            <input v-bind="field" placeholder="Last Name" />
            <p v-if="meta.touched && errorMessage" class="error">{{ errorMessage }}</p>
          </Field>
        </Input>

        <Input>
          <Field name="userName" v-slot="{ field, errorMessage, meta }">
            <input v-bind="field" placeholder="User Name" />
            <p v-if="meta.touched && errorMessage" class="error">{{ errorMessage }}</p>
          </Field>
        </Input>

        <Input>
          <Field name="email" v-slot="{ field, errorMessage, meta }">
            <input v-bind="field" type="email" placeholder="Email" />
            <p v-if="meta.touched && errorMessage" class="error">{{ errorMessage }}</p>
          </Field>
        </Input>

        <Input>
          <Field name="password" v-slot="{ field, errorMessage, meta }">
            <input v-bind="field" :type="type" placeholder="Password" />
            <Icon :type="type" @click="toggleType" />
            <p v-if="meta.touched && errorMessage" class="error">{{ errorMessage }}</p>
          </Field>
        </Input>

        <Input>
          <Field name="confirmPassword" v-slot="{ field, errorMessage, meta }">
            <input v-bind="field" :type="typeConfirmation" placeholder="Confirm Password" />
            <Icon :type="typeConfirmation" @click="toggleConfirmationType" />
            <p v-if="meta.touched && errorMessage" class="error">{{ errorMessage }}</p>
          </Field>
        </Input>

        <SubmitBtn title="Register" type="submit" />
      </Form>

      <LinkText>
        Already have an account?
        <RouterLink to="/login">Log in</RouterLink>
      </LinkText>
    </Container>
  </Section>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue';
import { useRouter } from 'vue-router';
import { Form, Field, useForm } from 'vee-validate';
import * as Yup from 'yup';
import { authApi } from '../utils/utils/authApi';

import Container from './Container.vue';
import Section from './Section.vue';
import Input from './Input.vue';
import LinkText from './LinkText.vue';
import SubmitBtn from './SubmitBtn.vue';
import FormTitle from './FormTitle.vue';
import Icon from './Icon.vue';

const router = useRouter();

const type = ref<'text' | 'password'>('password');
const typeConfirmation = ref<'text' | 'password'>('password');

const toggleType = () => {
  type.value = type.value === 'password' ? 'text' : 'password';
};

const toggleConfirmationType = () => {
  typeConfirmation.value = typeConfirmation.value === 'password' ? 'text' : 'password';
};

const schema = Yup.object({
  firstName: Yup.string().required().min(3, 'Minimum 3 characters'),
  lastName: Yup.string().required().min(3, 'Minimum 3 characters'),
  userName: Yup.string().required().min(3, 'Minimum 3 characters'),
  email: Yup.string().required().email('Invalid email format'),
  password: Yup.string()
    .required()
    .min(8, 'Minimum 8 characters')
    .matches(/[A-Z]/, 'At least one uppercase letter')
    .matches(/[a-z]/, 'At least one lowercase letter')
    .matches(/[0-9]/, 'At least one number')
    .matches(/[!@#$%^&*]/, 'At least one special character'),
  confirmPassword: Yup.string()
    .required('Confirm your password')
    .oneOf([Yup.ref('password')], 'Passwords must match'),
});

const onSubmit = async(values) =>{
  try {
    await authApi.register(values);
    router.push('/login');
  } catch (err) {
    console.error(err);
  }
}

</script>

<style scoped lang="scss">
.wrap {
  display: flex;
  flex-wrap: wrap;
  width: 100%;
  gap: 20px;
  max-width: 600px;
  margin: 0 auto;
  justify-content: center;
  margin-bottom: 40px;
}

.error {
  color: red;
  position: absolute;
  right: 50%;
  transform: translateX(50%);
  top: 100%;
  width: 100%;
}
</style>

// react-frontend/src/components/RegisterForm.tsx
import * as Yup from "yup";
import { Formik, Form, Field } from "formik";
import styled from "styled-components";
import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";

import { authApi } from "../utils/utils/authApi";

import Container from "./Container";
import Section from "./Section";
import Input from "./Input";
import LinkText from "./LinkText";
import SubmitBtn from "./SubmitBtn";
import FormTitle from "./FormTitle";
import Icon from "./Icon";

const FormWrap = styled.div`
  display: flex;
  flex-wrap: wrap;
  width: 100%;
  gap: 20px;
  max-width: 600px;
  margin: 0 auto;
  justify-content: center;
  margin-bottom: 40px;
`;
const ErrorText = styled.p`
  color: red;
  position: absolute;
  right: 50%;
  transform: translateX(50%);
  top: 100%;
  width: 100%;
`;

const RegisterForm = () => {
  const navigate = useNavigate();
  const [type, setType] = useState<"password" | "text">("password");
  const [typeConfirmation, setTypeConfirmation] = useState<"password" | "text">(
    "password"
  );

  const toggleType = () =>
    type === "password" ? setType("text") : setType("password");
  const toggleConfirmationType = () =>
    typeConfirmation === "password"
      ? setTypeConfirmation("text")
      : setTypeConfirmation("password");

  return (
    <Section>
      <Container>
        <FormTitle title={"Create your own TODO list :)"} />
        <Formik
          initialValues={{
            firstName: "",
            lastName: "",
            userName: "",
            password: "",
            confirmPassword: "",
            email: "",
          }}
          onSubmit={async (values) => {
            console.log(values);
            const data = await authApi.register(values);
            console.log(data);
            navigate("/login");
          }}
          validationSchema={Yup.object().shape({
            firstName: Yup.string().min(3).required().label("First name"),
            userName: Yup.string().min(3).required().label("User name"),
            lastName: Yup.string().min(3).required().label("Last name"),
            email: Yup.string().email().required().label("Email"),
            password: Yup.string()
              .required()
              .label("Password")
              .matches(
                /^(?=.*[A-Z])/,
                "Password must contain at least one uppercase letter"
              )
              .matches(
                /^(?=.*[a-z])/,
                "Password must contain at least one lowercase letter"
              )
              .matches(
                /^(?=.*[0-9])/,
                "Password must contain at least one number"
              )
              .matches(
                /^(?=.*[!@#$%^&*])/,
                "Password must contain at least one special character"
              )
              .matches(
                /^(?=.{8,})/,
                "Password must contain at least 8 characters"
              ),
            confirmPassword: Yup.string()
              .required()
              .label("Confirm password")
              .oneOf([Yup.ref("password")], "Password shoud match"),
          })}
        >
          {({ values, handleChange, handleBlur, handleSubmit, errors }) => {
            return (
              <Form>
                <FormWrap>
                  <Input>
                    <Field
                      type="text"
                      name="firstName"
                      onChange={handleChange}
                      value={values.firstName}
                      onBlur={handleBlur}
                      placeholder={"First Name"}
                    />
                    {errors.firstName && (
                      <ErrorText>{errors.firstName}</ErrorText>
                    )}
                  </Input>
                  <Input>
                    <Field
                      type="text"
                      name="lastName"
                      onChange={handleChange}
                      value={values.lastName}
                      onBlur={handleBlur}
                      placeholder={"Last Name"}
                    />
                    {errors.lastName && (
                      <ErrorText>{errors.lastName}</ErrorText>
                    )}
                  </Input>
                  <Input>
                    <Field
                      type="text"
                      name="userName"
                      onChange={handleChange}
                      value={values.userName}
                      onBlur={handleBlur}
                      placeholder={"User Name"}
                    />
                    {errors.userName && (
                      <ErrorText>{errors.userName}</ErrorText>
                    )}
                  </Input>
                  <Input>
                    <Field
                      type="email"
                      name="email"
                      value={values.email}
                      onBlur={handleBlur}
                      onChange={handleChange}
                      placeholder={"Email"}
                    />
                    {errors.email && <ErrorText>{errors.email}</ErrorText>}
                  </Input>
                  <Input>
                    <Field
                      type={type}
                      name="password"
                      onChange={handleChange}
                      onBlur={handleBlur}
                      value={values.password}
                      placeholder={"Password"}
                    />
                    <Icon onClick={toggleType} type={type} />
                    {errors.password && (
                      <ErrorText>{errors.password}</ErrorText>
                    )}
                  </Input>
                  <Input>
                    <Field
                      type={typeConfirmation}
                      name="confirmPassword"
                      onChange={handleChange}
                      onBlur={handleBlur}
                      value={values.confirmPassword}
                      placeholder={"Confirm password"}
                    />
                    <Icon
                      onClick={toggleConfirmationType}
                      type={typeConfirmation}
                    />
                    {errors.confirmPassword && (
                      <ErrorText>{errors.confirmPassword}</ErrorText>
                    )}
                  </Input>
                </FormWrap>

                <SubmitBtn
                  title={"Register"}
                  type="submit"
                  onClick={handleSubmit}
                />
              </Form>
            );
          }}
        </Formik>
        <LinkText>
          {"Already have an account?"}
          <Link to={"/login"}> {"Log in"}</Link>
        </LinkText>
      </Container>
    </Section>
  );
};

export default RegisterForm;
