// nextjs-frontend/src/components/Loader.tsx
import { Watch } from "react-loader-spinner";

const Loader = () => {
  return (
    <div className="fixed inset-0 w-screen h-screen bg-[#333] bg-opacity-50">
      <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2">
        <Watch
          height="200"
          width="200"
          radius="48"
          color="teal"
          ariaLabel="watch-loading"
          wrapperStyle={{}}
          visible={true}
        />
      </div>
    </div>
  );
};

export default Loader;

// vue-frontend/src/components/Loader.vue
<template>
  <div class="overlay">
  <div class="loader">
  <VueSpinnerClock size="200" color="teal" radius="50" />
  </div></div>
</template>

<script setup lang="ts">
import {  VueSpinnerClock} from 'vue3-spinners';

</script>

<style scoped>
.overlay {
  position: fixed;
  inset: 0;
  width: 100vw;
  height: 100vh;
  background-color: #333;
  opacity: 0.5;
  z-index: 1000;
}
.loader {
    position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}
</style>
