// src/components/TodoList.tsx
import styled from "styled-components";

import ITodo from "../interfaces/Todo.interface";
import TodoItem from "./TodoItem";

const List = styled.ul`
  display: flex;
  flex-wrap: wrap;
  flex-grow: 1;
  gap: 20px;
`;
interface IProps {
  todoList: ITodo[];
  token: string;
  refreshData(): void;
}
const TodoList = ({
  todoList,
  token,
  refreshData = async () => {},
}: IProps) => {
  return (
    <List>
      {todoList.map((el) => {
        return (
          <TodoItem
            token={token}
            refreshData={async () => await refreshData()}
            key={el._id}
            el={el}
          />
        );
      })}
    </List>
  );
};

export default TodoList;

// vue-frontend/src/components/TodoList.vue
<template>
  <ul class="list">
    <TodoItem
      v-for="el in todoList"
      :key="el._id"
      :token="token"
      :refresh-data="refreshData"
      :el="el"
    />
  </ul>
</template>

<script setup lang="ts">
import TodoItem from "./TodoItem.vue";
import { defineProps } from "vue";

interface TodoListProps {
  todoList: { title: string; isCompleted: boolean; _id: string }[];
  token: string;
  refreshData?: () => void;
}
withDefaults(defineProps<TodoListProps>(), {
  refreshData: () => {},
});
</script>

<style scoped lang="scss">
.list {
  display: flex;
  flex-wrap: wrap;
  gap: 20px;
  padding: 0;
  margin: 0;
  box-sizing: border-box;
  flex-grow: 1;
}
</style>
