// vue-frontend/src/pages/TodoDetails.vue
<template>
  <div>
    <Header />
    <Section>
      <Container>
        <div class="back" @click="goBack">
          <IoIosArrowBack :size="25" color="teal" />
        </div>

        <div v-if="todo">
          <p>Task:</p>
          <Title :title="todo.title" />
          <p>Is completed:</p>
          <Title
            :title="
              todo.isCompleted
                ? 'Task is completed'
                : 'You should finish the task'
            "
          />
        </div>
      </Container>
    </Section>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from "vue";
import { useRouter, useRoute } from "vue-router";
import { IoIosArrowBack } from "vue3-icons/io";

import { todoListApi } from "../utils/utils/todoApi";
import type ITodo from "../utils/interfaces/Todo.interface";

import Header from "../components/Header.vue";
import Section from "../components/Section.vue";
import Container from "../components/Container.vue";
import Title from "../components/Title.vue";

const router = useRouter();
const route = useRoute();

const todo = ref<ITodo | null>(null);

const goBack = () => {
  router.push("/my-todo-list");
};

onMounted(async () => {
  const todoId = route.params.id as string | undefined;
  const token = localStorage.getItem("token");

  if (!todoId || !token) return;

  try {
    const response = await todoListApi.getByid(todoId, token);
    todo.value = response.data.todo;
  } catch (error) {
    console.error(error);
  }
});
</script>

<style scoped lang="scss">
.back {
  margin-bottom: 40px;
  cursor: pointer;
}
</style>

// angular-frontend/src/app/components/todo-details/todo-details.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router, RouterModule } from '@angular/router';
import { CommonModule } from '@angular/common';

import { todoListApi } from '../../utils/utils/todoApi';

import { Loader } from '../loader/loader';
import { Title } from '../title/title';
import { Section } from '../section/section';
import { Container } from '../container/container';
import { Header } from '../header/header';

@Component({
  selector: 'app-todo-details',
  imports: [
    CommonModule,
    RouterModule,
    Header,
    Section,
    Container,
    Title,
    Loader,
  ],
  templateUrl: './todo-details.html',
  styleUrl: './todo-details.scss',
})
export class TodoDetails implements OnInit {
  id = '';
  token = '';
  todo: any = null;
  isLoading = false;

  constructor(private route: ActivatedRoute, private router: Router) {}

  ngOnInit(): void {
    this.token = localStorage.getItem('token') || '';
    this.id = this.route.snapshot.paramMap.get('id') || '';
    if (this.id && this.token) {
      this.getTodo();
    }
  }

  async getTodo() {
    try {
      this.isLoading = true;
      const res = await todoListApi.getByid(this.id, this.token);
      this.todo = res.data.todo;
    } catch (error) {
      console.error(error);
    } finally {
      this.isLoading = false;
    }
  }

  goBack() {
    this.router.navigate(['/my-todo-list']);
  }
}
