// react-frontend/src/components/FormTitle.tsx
import type React from "react";
import styled from "styled-components";

const Title = styled.h1`
  font-size: 35px;
  text-align: center;
  color: teal;
  margin: 0 auto;
  width: fit-content;
  margin-bottom: 60px;
`;

interface FormTitleProps {
  title: string;
}
const FormTitle: React.FC<FormTitleProps> = ({ title }) => {
  return <Title>{title}</Title>;
};

export default FormTitle;

// nuxtjs-frontend/components/FormTitle.vue
<template>
  <h1 class="title">{{title}}</h1>
</template>

<script setup lang="ts">
interface FormTitleProps {
  title: string;
}
const props = defineProps<FormTitleProps>()
const { title } = props;
</script>

<style scoped lang="scss">
.title {
 font-size: 35px;
  text-align: center;
  color: teal;
  margin: 0 auto;
  width: fit-content;
  margin-bottom: 60px;
}
</style>
