// nextjs-frontend/src/components/Modal.tsx
import { useEffect, useState } from "react";
import { AiOutlineClose } from "react-icons/ai";

interface IProps {
  todo?: string;
  btnTitle?: string;
  closeModal(): void;
  updateTodo(val: string): void;
}
const Modal = ({
  todo = "",
  updateTodo,
  closeModal,
  btnTitle = "Edit",
}: IProps) => {
  const [value, setValue] = useState(todo);

  const saveChanges = (e: KeyboardEvent) => {
    const valueFromInput = (e.target as HTMLInputElement).value;

    if (e.key === "Enter") updateTodo(valueFromInput);
  };

  useEffect(() => {
    document.addEventListener("keyup", saveChanges);
    return () => {
      document.removeEventListener("keyup", saveChanges);
    };
  }, []);

  return (
    <div
      className="fixed inset-0 w-screen h-screen bg-black bg-opacity-60"
      onClick={(e) => {
        if (e.target === e.currentTarget) closeModal();
      }}
    >
      <div
        className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 bg-white rounded-md p-8 min-w-[500px] max-w-full
  max-sm:min-w-[290px]"
      >
        <span
          className="flex justify-center items-center absolute top-5 right-5 cursor-pointer"
          onClick={closeModal}
        >
          <AiOutlineClose />
        </span>
        <p className="text-base mb-2.5">{"Next up:"}</p>
        <input
          value={value}
          onChange={(e) => setValue(e.target.value)}
          className="min-h-[40px] min-w-[200px] p-[7px] bg-transparent border border-gray-300 rounded-md outline-none"
        />
        <button
          className="bg-teal-600 text-white border border-teal-600 cursor-pointer outline-none flex justify-center items-center p-[7px] min-w-[200px] min-h-[40px] box-border ml-auto rounded-md mt-10 transition-all duration-250 ease-[cubic-bezier(0.175,0.885,0.32,1.275)] hover:bg-white hover:text-teal-600"
          onClick={() => updateTodo(value)}
        >
          {btnTitle}
        </button>
      </div>
    </div>
  );
};

export default Modal;

// nuxtjs-frontend/components/Modal.vue
<template>
  <div class="backdrop">
    <div class="modal">
      <span class="close" @click="closeModal">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
          stroke-width="1.5"
          stroke="currentColor"
          class="size-6"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            d="M6 18 18 6M6 6l12 12"
          />
        </svg>
      </span>
      <p class="title">Next up:</p>
      <input v-model="value" @keyup.enter="handleEnter" />
      <button class="btn" @click="updateTodo(value)">{{ btnTitle }}</button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from "vue";

interface ModalProps {
  todo?: string;
  updateTodo: (value: string) => void;
  closeModal?: () => void;
  btnTitle?: string;
}
const props = defineProps<ModalProps>();
const { updateTodo, closeModal } = props;

const value = ref(props.todo || "");

const btnTitle = props.btnTitle || "Edit";

const handleEnter = () => {
  if (value.value.trim()) {
    updateTodo(value.value);
  }
};

const handleKeyUp = (e: KeyboardEvent) => {
  if (e.key === "Enter") {
    handleEnter();
  }
};

onMounted(() => {
  document.addEventListener("keyup", handleKeyUp);
});

onUnmounted(() => {
  document.removeEventListener("keyup", handleKeyUp);
});
</script>

<style scoped lang="scss">
.backdrop {
  position: fixed;
  top: 0;
  bottom: 0;
  right: 0;
  left: 0;
  width: 100vw;
  height: 100vh;
  background-color: rgba(0, 0, 0, 0.1);
  box-sizing: border-box;
}
.modal {
  position: absolute;
  box-sizing: border-box;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  background-color: #fff;
  border-radius: 5px;
  padding: 30px;
  max-width: 500px;
  min-width: 500px;
  input {
    min-height: 40px;
    min-width: 200px;
    padding: 7px;
    background-color: transparent;
    border: 1px solid #ccc;
    outline: none;
    border-radius: 4px;
    box-sizing: border-box;
    cursor: pointer;
  }
  @media only screen and (max-width: 575px) {
    max-width: 290px;
    min-width: 290px;
  }
}
.close {
  display: flex;
  justify-content: center;
  align-items: center;
  position: absolute;
  top: 20px;
  right: 20px;
  cursor: pointer;
  width: 20px;
}
.title {
  font-size: 16px;
  margin-bottom: 10px;
}
.btn {
  background-color: teal;
  color: #fff;
  border: 1px solid teal;
  cursor: pointer;
  outline: none;
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 7px;
  min-width: 200px;
  min-height: 40px;
  box-sizing: border-box;
  margin-left: auto;
  border-radius: 4px;
  margin-top: 40px;
  transition: all 250ms cubic-bezier(0.175, 0.885, 0.32, 1.275);
  &:hover,
  &:focus {
    background-color: #fff;
    color: teal;
  }
}
</style>
